version: '3.8'

services:
  web:
    build: .
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db/myapp_development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp_development
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
