databases:
  - name: filmusic_DB
    databaseName: filmusic
    user: filmusic
    region: singapore

services:
  - type: web
    name: filmusic
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filmusic_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

